# -*- coding: utf-8 -*-
"""4.Random Image  Generator python project Exam (27).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xFjAo9zbRbK2YQUBOTxsTbIJmzboAEwD
"""

!pip install numpy pillow

from PIL import Image
import numpy as np
import random

# Set image size
width, height = 256, 256

# Ask user for type of image
mode = input("Enter image mode (grayscale/color): ").lower()

if mode == "grayscale":
    # Create random grayscale image
    gray_array = np.random.randint(0, 256, (height, width), dtype=np.uint8)
    img = Image.fromarray(gray_array, 'L')
    img.save("random_grayscale.png")
    print("Grayscale image saved as 'random_grayscale.png'")

elif mode == "color":
    # Create random RGB image
    color_array = np.random.randint(0, 256, (height, width, 3), dtype=np.uint8)
    img = Image.fromarray(color_array, 'RGB')
    img.save("random_color.png")
    print("Color image saved as 'random_color.png'")

else:
    print("Invalid input. Please enter 'grayscale' or 'color'.")

from google.colab import files
files.download('random_color.png')